
  services:
  - type: web
    name: medication-info-api
    runtime: python
    buildCommand: poetry install --no-dev
    startCommand: poetry run uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: AIzaSyBGYP8YdFfNZ6XgbVgny9BoCGSRLGBGvCg
        fromGroup: gemini
      - key: PORT
        value: 8000