services:
  - type: web
    name: medication-info-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: AIzaSyBGYP8YdFfNZ6XgbVgny9BoCGSRLGBGvCg
        fromGroup: gemini